@startuml
'https://plantuml.com/class-diagram

class ToDoList{
    main()
    start()
}

class ToDoListController implements Initializable{

button Update;
button Delete;

addItemclicked()
initialize()
saveButtonClicked()
restoreButtonClicked()
readFile()

}

class Item{
 String description;
 String dueDate;
 String status;
 String statusDate;

}

class AddItemController implements Initializable{

    TextField inputDesc;
    DatePicker inputDueDate;
    Button cancel;
    Button save;

    setTableItems()
    infoToUpdate()
    handleButtonAction()


}

javafx.Application <|--ToDoList

ToDoList- ToDoListController

@enduml